### ISSUE TITLE
Wartungsseite: Historische Betreuungen - "200 frühere Ergeinisse" funktioniert nicht

### ISSUE THREAD

**Issue by rkraasch** [tool-labs/mp#1]
Auf der Seite https://mp.toolforge.org/index.php?action=maintenance_mm_history funktioniert der Link "200 frühere Ergeinisse >>>" nicht.
(Also https://mp.toolforge.org/index.php?action=maintenance_mm_history&end_time=2024-04-10%2009:40:23&limit=200)

Gruß
Reinhard

**Comment by euku** [comment]
Danke für die Meldung. Ist nun behoben.
